# Generated by Django 2.2.4 on 2019-09-25 21:41

import PictoApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.FileField(blank=True, upload_to=PictoApp.models.subir_imagen),
        ),
    ]
