# Generated by Django 2.2.4 on 2019-09-25 23:29

import PictoApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictoApp', '0002_auto_20190925_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='sonido',
            field=models.FileField(blank=True, null=True, upload_to=PictoApp.models.subir_sonido),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=PictoApp.models.subir_imagen),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='titulo',
            field=models.CharField(max_length=35),
        ),
    ]
