# Generated by Django 2.2.4 on 2019-09-27 19:35

import PictoApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictoApp', '0003_auto_20190925_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=35)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=PictoApp.models.subir_imagen)),
                ('sonido', models.FileField(blank=True, null=True, upload_to=PictoApp.models.subir_sonido)),
            ],
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
