# Generated by Django 2.2.4 on 2019-09-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictoApp', '0004_auto_20190927_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='titulo',
            field=models.TextField(max_length=35),
        ),
    ]
