# Generated by Django 2.2.4 on 2019-09-28 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PictoApp', '0005_auto_20190927_2100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagens',
            new_name='BDPictogramas',
        ),
    ]
