# Generated by Django 2.2.4 on 2019-09-28 10:39

import PictoApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictoApp', '0007_bdpictogramas_locucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdpictogramas',
            name='locucion',
            field=models.FileField(blank=True, null=True, upload_to=PictoApp.models.subir_locucion),
        ),
    ]
