# Generated by Django 2.2.4 on 2019-09-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictoApp', '0008_auto_20190928_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciertos', models.IntegerField(max_length=10)),
                ('errores', models.IntegerField(max_length=10)),
            ],
        ),
    ]
