# Generated by Django 2.2.4 on 2019-09-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictoApp', '0009_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='aciertos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='errores',
            field=models.IntegerField(),
        ),
    ]
