# Generated by Django 2.2.4 on 2019-10-02 15:28

import PictoApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PictoApp', '0010_auto_20190928_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('cuadro', models.ImageField(null=True, upload_to=PictoApp.models.subir_categoria)),
            ],
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bdpictogramas',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PictoApp.Categorias'),
        ),
    ]
