# Generated by Django 2.2.4 on 2019-10-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictoApp', '0011_auto_20191002_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
