# Generated by Django 2.2.4 on 2019-10-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictoApp', '0012_auto_20191002_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdpictogramas',
            name='consonido',
            field=models.CharField(choices=[('si', 'Tiene'), ('no', 'No tiene')], default=(('si', 'Tiene'), ('no', 'No tiene')), max_length=1),
        ),
    ]
