# Generated by Django 2.2.4 on 2019-10-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictoApp', '0013_bdpictogramas_consonido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdpictogramas',
            name='consonido',
            field=models.IntegerField(choices=[('si', 'Tiene'), ('no', 'No tiene')], default=(('si', 'Tiene'), ('no', 'No tiene')), max_length=20),
        ),
    ]
