# Generated by Django 2.2.4 on 2019-10-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictoApp', '0014_auto_20191016_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdpictogramas',
            name='consonido',
            field=models.IntegerField(choices=[(1, 'Tiene'), (2, 'No tiene')], default=((1, 'Tiene'), (2, 'No tiene'))),
        ),
    ]
