# Generated by Django 2.2.4 on 2019-10-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictoApp', '0015_auto_20191016_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdpictogramas',
            name='consonido',
            field=models.IntegerField(choices=[('si', 'Tiene'), ('no', 'No tiene')], default=(('si', 'Tiene'), ('no', 'No tiene'))),
        ),
    ]
