# Generated by Django 2.2.4 on 2019-10-28 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PictoApp', '0017_auto_20191016_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='catelegida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PictoApp.Categorias'),
        ),
    ]
