# Generated by Django 2.2.4 on 2019-10-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictoApp', '0020_auto_20191030_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='color',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
