# Generated by Django 2.2.4 on 2019-10-31 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PictoApp', '0021_categorias_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='color',
        ),
    ]
